AB#824 Create search box
Bambitcompl/Bambit.Alfarm.App pull request #6
Opened 2022-03-05 20:34 UTC by szymonbla

2022-03-05 21:19 UTC, JKrymarys commented
The paddings between placeholder/searched text seems to be too much... definetely the components looks a bit bigs comparing to mocks. 

In figma there is 16px, while you have 4px (on text) and 16px (between text and border) 

![image](https://user-images.githubusercontent.com/17932699/156900187-6fa69803-034c-46cf-ab8a-2870a224ca09.png)

![image](https://user-images.githubusercontent.com/17932699/156900198-fe88a4c1-d6ad-4fb8-8177-20722165a9b1.png)

2022-03-05 21:27 UTC, JKrymarys commented
Looking deeper, there is also some padding on button/icon element. Anyway instead of overriding everything I'd change padding `<Box>` (Seachbox.tsx line 11) that all combined gives desired value (and look good :)).

2022-03-05 21:29 UTC, JKrymarys requested changes

2022-03-05 21:29 UTC, JKrymarys commented on src/common/components/SearchBox/SearchBox.tsx
> +        p: (theme) => theme.spacing(2)
Adjust the padding to match designs (I explained it more in a PR comment)

2022-03-05 22:14 UTC, szymonbla commented on src/common/components/SearchBox/SearchBox.tsx
> +        p: (theme) => theme.spacing(2)
Thanks for the suggestions. Summing up, I moved padding to the ```MuiInputBase-input```. It seems that's work. Additionally, I adjusted the button/icon search styling, I hope now it's better

2022-03-06 15:53 UTC, JKrymarys approved these changes
LGTM now

2022-03-06 18:06 UTC, merged