[WIP] Implement category list component
Bambitcompl/Bambit.Alfarm.App pull request #7
Opened 2022-03-06 22:17 UTC by szymonbla

2022-03-07 18:54 UTC, JKrymarys commented on src/common/Sandbox/Sandbox.tsx
> +          categories={[
Let's extract this array to some file like `~/common/constants/categories.ts`

2022-03-07 18:56 UTC, JKrymarys commented on src/common/Sandbox/Sandbox.tsx
> +          categories={[
oh, it's in sandbox.... so maybe only `~/sandbox/constants.ts`

2022-03-07 18:57 UTC, JKrymarys commented on src/common/components/CategoriesList/types/categorieItemType.ts
> +  img?: React.ElementType<SvgIconComponent>;
Let's put optional props in the end, to make it more organised

2022-03-07 19:09 UTC, JKrymarys commented on src/common/components/CategoriesList/CategoriesList.tsx
> +  const [active, setActive] = useState<number>(1);
No, we cannot have it like this. Please refactor it to use category key (not the index) as a "active" indicator. 

Also we will need to move this data somewhere else, as other components will need to know which category is active

2022-03-07 19:15 UTC, JKrymarys commented on src/common/Sandbox/Sandbox.tsx
> +          categories={[
Also I'd propose following fields: 

{
 id: string //category key 
 label: string // previous title 
 tagColor: string
 icon: icon component // optional 
 counter: number // optional
}

2022-03-07 19:19 UTC, JKrymarys commented on src/common/components/CategoriesList/CategorieItem/CategorieItem.tsx
> +  active: number;
Thinking out load I think that I'd rather have here 'isActive' boolean property... 

The item component doesn't need the info which category is open, but it only needs to know whether they are in an active state or not

2022-03-07 19:20 UTC, JKrymarys commented on src/common/components/CategoriesList/CategorieItem/CategorieItem.tsx
> +        backgroundColor: `${active === index && (index === 1 ? tagColor : `${tagColor}50`)}`,
Which `isActive` boolean, you don't need this comparisons here.

Also I don't understand why one of the tabs have different `backgroundColor` formula...

2022-03-07 19:20 UTC, JKrymarys commented on src/common/components/CategoriesList/CategorieItem/CategorieItem.tsx
> +          backgroundColor: `${index === 1 ? tagColor : `${tagColor}50`}`,
Ditto. I don't understand why one of the tabs have different backgroundColor formula...

2022-03-07 19:21 UTC, JKrymarys commented on src/common/components/CategoriesList/CategorieItem/CategorieItem.tsx
> +          <SvgIcon
Let's make a component "ColorfulTagIcon" which takes color as a prop

2022-03-07 19:22 UTC, JKrymarys commented on src/common/components/CategoriesList/CategorieItem/CategorieItem.tsx
> +      <Typography sx={{ typography: 'body1', fontWeight: `${active === index ? 600 : 500}` }}>{title}</Typography>
Like we discussed on discord. 

Imo in case of components that have some variants/api let's use before putting that in `sx`.

2022-03-07 19:24 UTC, JKrymarys commented on src/common/components/CategoriesList/CategoriesList.tsx
> +  const [active, setActive] = useState<number>(1);
Probably it should be in redux, but for now let's make it here in a state and refactor it when we'll compose the whole page (but please add some TODO comment to not forget about it :))

2022-03-07 19:27 UTC, JKrymarys requested changes

2022-03-07 19:27 UTC, JKrymarys commented on src/common/components/CategoriesList/types/categorieItemType.ts
> +export type CategorieItemData = {
We need to have some id of category here. What about sth like this? 
```
{
 id: string //category key 
 label: string // previous title 
 tagColor: string
 icon?: icon component // optional 
 counter?: number // optional
}
```

2022-03-07 19:27 UTC, JKrymarys commented on src/common/components/CategoriesList/CategorieItem/CategorieItem.tsx
> +export const CategorieItem = ({ img, title, counter, tagColor, index, active, setActive }: CategorieItemProps) => {
I think that it should be `CategoryItem`. `Categorie` sounds a bit french :P

2022-03-08 09:04 UTC, szymonbla commented on src/common/components/CategoriesList/CategorieItem/CategorieItem.tsx
> +        backgroundColor: `${active === index && (index === 1 ? tagColor : `${tagColor}50`)}`,
The main reason is that the suggested colour with the opacity doesn't meet the UI requirements (it is almost invisible). I am completely open to new ideas/thoughts, but it seemed to be the best solution.

2022-03-08 09:06 UTC, szymonbla commented on src/common/components/CategoriesList/CategorieItem/CategorieItem.tsx
> +          backgroundColor: `${index === 1 ? tagColor : `${tagColor}50`}`,
Tried to explain in the thread above.

2022-03-08 09:09 UTC, szymonbla commented on src/common/components/CategoriesList/CategorieItem/CategorieItem.tsx
> +      <Typography sx={{ typography: 'body1', fontWeight: `${active === index ? 600 : 500}` }}>{title}</Typography>
Obviously. I made PR before your reply 😅

2022-03-08 09:19 UTC, szymonbla commented on src/common/components/CategoriesList/types/categorieItemType.ts
> +  img?: React.ElementType<SvgIconComponent>;
Indeed. I did it in another file, but the types folder went out of my mind.

2022-03-08 15:03 UTC, pmakowski23 commented on src/common/components/CategoriesList/CategorieItem/CategorieItem.tsx
> +        backgroundColor: `${active === index && (index === 1 ? tagColor : `${tagColor}50`)}`,
Maybe we should separate the logic and create 
- `Main category` here "Odebrane" 
- `Sub categories` which would be here "Rozliczenia", "Ekspozycja" etc.

2022-03-08 22:18 UTC, pmakowski23 requested changes

2022-03-08 22:18 UTC, pmakowski23 commented on src/common/Sandbox/Sandbox.tsx
> +import { CategorieListConfig } from './constants';
Maybe you could change all `Categorie` to `Category` for consistency

2022-03-08 22:18 UTC, pmakowski23 commented on src/common/components/CategoriesList/CategoriesList.tsx
> +// isMain = {
Why leave comments?

2022-03-08 22:18 UTC, pmakowski23 commented on src/common/components/CategoriesList/CategoriesList.tsx
> +          isActive={active === index ? true : false}
Can't this be `active === index`?

2022-03-09 07:49 UTC, szymonbla commented on src/common/components/CategoriesList/CategoriesList.tsx
> +// isMain = {
[WIP]

2022-03-11 12:35 UTC, JKrymarys commented on src/common/components/CategoryList/CategoryItem/CategoryItem.tsx
> +      {counter !== undefined && counter > 0 && (
Hmm what if there are no messages and the counter should be 0?

2022-03-11 12:36 UTC, JKrymarys commented on src/common/components/CategoryList/CategoryItem/CategoryItem.tsx
> +      {counter !== undefined && counter > 0 && (
@mkidawa how should it behave?

2022-03-11 12:39 UTC, JKrymarys commented on src/common/components/CategoryList/types/categoryItemType.ts
> +  // id: string;
Why commented?

"Try not. Do or do not, there is no try" ~ Yoda

2022-03-11 12:46 UTC, szymonbla commented on src/common/components/CategoryList/CategoryItem/CategoryItem.tsx
> +      {counter !== undefined && counter > 0 && (
If the counter is 0, the component should not render according to Michal message

2022-03-11 12:49 UTC, szymonbla commented on src/common/components/CategoryList/types/categoryItemType.ts
> +  // id: string;
Why not? XD 
Frankly speaking, should I assign an index to id in ``` CategoryList ``` component?

2022-03-11 16:34 UTC, JKrymarys commented on src/common/components/CategoryList/types/categoryItemType.ts
> +  // id: string;
Personally I would like to have 'id' of each category and use it to explicitly keep track on which one is active. I know that you did that by index, but I prefer to see name than number

2022-03-11 21:05 UTC, szymonbla commented on src/common/components/CategoryList/types/categoryItemType.ts
> +  // id: string;
I propose to assign a label as an identifier. You will no doubt be able to follow the active category.

2022-03-12 09:57 UTC, JKrymarys commented on src/common/components/CategoryList/types/categoryItemType.ts
> +  // id: string;
I was thinking about that, but not sure if having special characters (like ó in 'Ogólne') won't cause us any troubles in the future

2022-03-12 21:21 UTC, szymonbla commented on src/common/components/CategoryList/types/categoryItemType.ts
> +  // id: string;
@JKrymarys I will stay with the numbers or assign an id for each category without any special characters. I believe that the first option is better for now. In case of problems adding id won't be a problem.

2022-03-13 15:16 UTC, merged